### ISSUE TITLE
how to set the slider value after initialization?

### ISSUE THREAD

**Issue by ccorcos** [turban/d3.slider#14]
```
d3.select("#link-strength-slider")
    .call(d3.slider()
        .min(0)
        .max(1)
        .step(0.05)
        .value(Session.get("linkStrength"))
        .on("slide", function(evt, value) {
            Session.set("linkStrength", value);
            // force.stop();
            force = force.linkStrength(value);
            force.start();
        }));
```

later on I want to do something like

```
$("#link-strength-slider").val(10)
```

any ideas?

**Comment by wahlatlas** [comment]
This is possible since François' commit from Sept 29, 2014. https://github.com/turban/d3.slider/commit/bb33d878b627d4c20c13212b75fd50d1ca1abcad

    var mySlider = d3.slider()
        .min(0)
        .max(1)
        .step(0.05)
        .value(Session.get("linkStrength"))
        .on("slide", function(evt, value) {
            Session.set("linkStrength", value);
            // force.stop();
            force = force.linkStrength(value);
            force.start();
        }); 

    d3.select("#link-strength-slider")
    .call(mySlider);

    mySlider.value(newValue);
